services:
  server:
    image: 266359798421.dkr.ecr.us-west-1.amazonaws.com/recur-api:latest
    ports:
      - "8000:8000"
    env_file:
      - ./server/.env

  client:
    image: 266359798421.dkr.ecr.us-west-1.amazonaws.com/recur-app:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - server