name: Build and Push Images

on:
  push:
    branches: ["main"]

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - uses: aws-actions/amazon-ecr-login@v2
      id: login-ecr

    - name: Build + Push Backend
      run: |
        BACKEND_URI=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_BACKEND }}:latest
        docker build -t $BACKEND_URI ./server
        docker push $BACKEND_URI

    - name: Build + Push Frontend
      run: |
        FRONTEND_URI=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_FRONTEND }}:latest
        docker build \
          --build-arg VITE_CLERK_PUBLISHABLE_KEY=${{ secrets.VITE_CLERK_PUBLISHABLE_KEY }} \
          --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
          -t $FRONTEND_URI ./client
        docker push $FRONTEND_URI

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd Subscription-Manager
          docker-compose pull
          docker-compose up -d